# Generated by Django 5.1.4 on 2025-01-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnserver',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
